### ISSUE TITLE
Implement make install

### ISSUE THREAD

**Issue by dvrogozh** [intel/gmmlib#18]
Please, implement make install for gmmlib. It should install the following:
* gmmlib libraries to CMAKE_INSTALL_LIBDIR (for example to /usr/lib64 on centos)
* CMAKE_INSTALL_LIBDIR/pkgconfig/gmmlib.pc - pkg-config file to be used by other project to use gmmlib as a build dependency
- CMAKE_INSTALL_INCLUDEDIR/gmmlib/*.h - gmmlib header files

**Comment by dvrogozh** [comment]
@drprajap: any update on this issue? Is there any patch which can be reviewed/tried - please, provide a PR for review? (@chivakker: FYI)

**Comment by drprajap** [comment]
Yes, this is in progress, we were working on first client's dll integration and packaging changes. The patch is coming out this week, will be adding you in the review.

**Comment by uartie** [comment]
I assume a5f23913150534f9e1c841b4d5a073a096315cf0 is meant to address this issue.  Unfortunately when building media-driver, the CMAKE_INSTALL_PREFIX is not honored and gmmlib is unconditionally installed to /usr/lib.  This breaks `make install` if user wants to install to custom prefix without sudo.  Please fix ASAP!

**Comment by uartie** [comment]
Can a5f23913150534f9e1c841b4d5a073a096315cf0 be reverted until a correct patch is available please?

**Comment by dvrogozh** [comment]
@drprajap : that's really important to follow open source practices to avoid introducing issues for others. In this situation this means:
1. Please, avoid direct submission of the changes to the Git
2. Create a pull request from user forked copy first with the proposed change to address an issue or implement a feature
3. Let PR to hang on while community will review it. If you need urgent review, please, ping people directly. The change we currently discuss is of _extreme_ importance. You will _really_ get pretty quick review from me, @uartie, @chivakker and I think a few others. You could ping us 3 for sure to get a review.

**Comment by chivakker** [comment]
If possible, make sure that bullets 2 and 3 from @dvrogozh are part of README file.  It is important to review these changes and  the problem will be pinpointed right away.

Also please add to your commit messages or PR summary a statement that says which issue is being address, i.e. Fixes #xxx.

**Comment by drprajap** [comment]
@uartie: Sorry for the miss, I have found out the issue and working on a fix. Due to our internal mirroring process, I will have to push the fix via our internal server this time, but I will create PR to review the fix.

@dvrogozh: I understand the practices but due to previous history of breaking interfaces/testing, we decided to run all of our changes via internal server to cover proper validation. But now we have stable product in open-source so I am working with team to make this bidirectional and work directly via pull requests for addressing issues. This will address above 3 bullets. 

@chivakker: sure will update README. We usually put Issue# with commit message and proper summary but because there will be following changes to address current issue (Issue #18), I have not mentioned/closed the issue yet in latest commit [a5f2391](https://github.com/intel/gmmlib/commit/a5f23913150534f9e1c841b4d5a073a096315cf0), 

In above mentioned patch, we have not incorporate all the clients requirements. We have been testing only Neo (intel-opencl) client integration with this change, Media driver is not ready to integrate gmmlib shared library hence more following changes are expected to completely fulfill this issue.

**Comment by drprajap** [comment]
This is the PR for fix - https://github.com/intel/gmmlib/pull/22, I am not able to request review from either of you, can you please take a look?

**Comment by drprajap** [comment]
@uartie , @dvrogozh , @chivakker: Let me know if recent gmmlib patches for packaging and install satisfy this issue requirement or not. If so, I will close the issue.

Thanks.

**Comment by uartie** [comment]
@drprajap it was my understanding that the current patches were only a partial solution to this issue.  For example, the `.pc` file is still missing the appropriate `Libs:` specification.

**Comment by drprajap** [comment]
yes @uartie you are right. Earlier when we prepared this patch, we thought of adding shared library packaging only due to upcoming transition. But client integration may take a while, so added static lib support later, hence some changes are still missing. I will upload PR for review to address remaining issues.

Thanks.

**Comment by drprajap** [comment]
We have addressed all the problems raised in this request, so closing the issue. Feel free to re-open it if you feel something is missed or problematic.
