### ISSUE TITLE
release 18.4.0 changed SONAME and broke compatibility

### ISSUE THREAD

**Issue by fenrus75** [intel/gmmlib#42]
Please keep binary compatibility between releases!

**Comment by ArchangeGabriel** [comment]
Why? Softwares are allowed to change soname, that’s why it’s versioned!

**Comment by ArchangeGabriel** [comment]
No, compat libraries is not because of ABI changes, but API changes (we have openssl-1.0 because some software did not update their API use, not because they are ABI incompatible with new versions).

I don’t care if you have gmmlib in Clear Linux or not, though I would find it funny that *Intel* Clear Linux does not package *Intel* gmmlib because upstream changes ABI sometimes.

P.S.: BTW, I’m not a gmmlib dev, I’m ArchLinux maintainer for gmmlib.

**Comment by eli-schwartz** [comment]
The definition of a soname, and so too the definition of the ABI compatibility you crave, is that it is something which requires all applications linked to it, to *rebuild* their applications with no code changes or resulting changes in functionality. It is thus formally incorrect to claim that anyone needs to provide two packages for it.

API changes are an unrelated concern, although if you want to preserve API compat you can of course provide multiple interfaces within a library...

**Comment by eli-schwartz** [comment]
@fenrus75 do you have a lot of closed-source software provided exclusively as prebuilt binaries which link to external gmmlib shared libraries? Because this is the only reason you would need to worry about providing multiple ABIs.

**Comment by fenrus75** [comment]
part of our userbase generally adds their own closed applications to their
system when they make their product.

(sometimes even graphics drivers they give as open source to a contractor
who adds enhancements and then gives back a binary)

**Comment by eli-schwartz** [comment]
If they are using their own closed applications, then I assume they have the source code and can rebuild it.

If they're using a contractor who enhances an open-source program, then the contract should require that they **receive the source code which they paid for the development of**, because that's just how contracted development works. Otherwise they're just asking for trouble on so many levels -- who tosses their source code in the garbage after they build a one-time binary? What happens if they need further improvements and the original contractor didn't bother to retain the source code, or else went out of business/switched industries?

In the worst-case scenario they're purchasing the use of software from a vendor, but the corporate purchase, bizarrely, does not include the right to the source code for customization/auditing purposes. In this case, I would *highly* recommend that said software not rely on fragile things like external libraries that may or may not be installed, may or may not go out of style in the computing industry, and yes, may or may not change ABI over the years. There is a very easy fix for this, that makes everyone happy: **use static linking**.

This is a complete non-issue.

**Comment by chivakker** [comment]
also this library has a strong dependency with other open source libraries that have not communicated their support for this new ABI.

**Comment by johnmach** [comment]
Hi,
Thanks for highlighting various aspects w.r.t ABI maintenance. We appreciate all the inputs. We will try to incorporate the same. However, new feature or product sometime results in unavoidable compatibility break which will be the utmost thing for us to do with no other alternative. 
Since current version is the stable ABI, I am closing this issue.
