### ISSUE TITLE
commit d6c3b56745798bdd0c7e4920ebb5b4192225c17b cause H264 encoder crash

### ISSUE THREAD

**Issue by qiushics** [intel/gmmlib#6]
Pre commit works well. Maybe system memeory allocation method changed?

[commit d6c3b56745798bdd0c7e4920ebb5b4192225c17b](https://github.com/intel/gmmlib/commit/d6c3b56745798bdd0c7e4920ebb5b4192225c17b)

[MediaSDK issue](https://github.com/Intel-Media-SDK/MediaSDK/issues/57)

**Comment by drprajap** [comment]
We changed the way clients handle Gmm context, and current debug points to issue in media initialization path where it uses invalid GmmClientContext handle, causing various failures due to garbage address. This will be addressed soon by media-driver, fix is under testing.

**Comment by drprajap** [comment]
Even though this issue should have been fixed by [a703ec7362fedede71940929a1a18d9577324173fd6c3b5](https://github.com/intel/media-driver/commit/a703ec7362fedede71940929a1a18d9577324173fd6c3b5) , We are reverting gmmlib change due to possible compatibility issue it may cause, if not properly coordinated with client. This will be reworked and new change will be pushed to avoid any other client side impact.

Reverted commit - [f7b5da59be9fcb1edc57394703e96ebaf59a39ff](https://github.com/intel/gmmlib/commit/f7b5da59be9fcb1edc57394703e96ebaf59a39ff)
